Swallow.Manage/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Mvc;
using Swallow.Entity;
using Microsoft.AspNet.Authorization;
using MongoDB.Driver;
using MongoDB.Driver.Linq;
using Swallow.Core;

namespace Swallow.Manage.Controllers {
    [Authorize]
    public class ArticleController : Controller {
        private int page_size = 999;

        private readonly IArticleDbForManage ArticleDb;
        public ArticleController(IArticleDbForManage db) {
            this.ArticleDb = db;
        }

        public IActionResult Item(string id) {
            var user = ArticleDb.Get(id);
            return View(user);
        }

        public IActionResult Index(
            ArticleStatus status = ArticleStatus.All,
            ArticleType type = ArticleType.All,
            ArticleVector vector = ArticleVector.All,
            string query = null,
            SortPattern pattern = SortPattern.Newest,
            int page = 1
        ) {
            var users = ArticleDb.Index(status, type, vector, query, pattern, page, page_size);
            ViewBag.Query = query;
            ViewBag.StatusSel = status.ToSelectListItems();
            ViewBag.TypeSel = type.ToSelectListItems();
            ViewBag.VectorSel = vector.ToSelectListItems();
            ViewBag.PatternSel = pattern.ToSelectListItems();
            return View(users.ToList()); // PagedList don't support asp.net5 about Razor so far
        }

        private void BuildCreateView() {
            ViewBag.StatusSel = ArticleStatus.Unapproved.ToSelectListItems();
            ViewBag.TypeSel = ArticleType.Unknow.ToSelectListItems();
            ViewBag.VectorSel = ArticleVector.Text.ToSelectListItems();
        }

        public ActionResult Create() {
            BuildCreateView();
            return View(new Article());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Article model) {
            BuildCreateView();
            ModelState.Remove("CreatDate");
            if (!ModelState.IsValid) {
                ModelState.AddModelError("", "表单验证失败。");
                return View(model);
            }
            string failure;
            model.UserId = User.Identity.Name;
            var user = ArticleDb.Create(model, out failure);
            if (!string.IsNullOrEmpty(failure) || user == null) {
                ModelState.AddModelError("", failure ?? "新建失败");
                return View(model);
            }
            return RedirectToAction("Index");
        }

        private void BuildEditView(Article article) {
            ViewBag.StatusSel = ((ArticleStatus)article.Status).ToSelectListItems();
            ViewBag.TypeSel = ((ArticleType)article.Type).ToSelectListItems();
            ViewBag.VectorSel = ((ArticleVector)article.Vector).ToSelectListItems();
        }

        public ActionResult Edit(string id) {
            var article = ArticleDb.Get(id);
            BuildEditView(article);
            return View(article);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Article model) {
            BuildEditView(model);
            ModelState.Remove("CreatDate");
            if (!ModelState.IsValid) {
                ModelState.AddModelError("", "表单验证失败。");
                return View(model);
            }
            string failure;
            var user = ArticleDb.Update(model, out failure);
            if (!string.IsNullOrEmpty(failure) || user == null) {
                ModelState.AddModelError("", failure ?? "更新失败");
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id, string failure) {
            var user = ArticleDb.Get(id);
            ViewBag.Failure = failure;
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id) {
            string failure;
            ArticleDb.Delete(id, out failure);
            if (!string.IsNullOrEmpty(failure))
                return RedirectToAction("Delete", new { id = id, failure = failure});
            return RedirectToAction("Index");
        }
    }
}

Swallow.Manage/Controllers/CaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Mvc;
using Swallow.Entity;
using Microsoft.AspNet.Authorization;
using MongoDB.Driver;
using MongoDB.Driver.Linq;
using Swallow.Core;

namespace Swallow.Manage.Controllers {
    [Authorize]
    public class CaseController : Controller {
        private int page_size = 999;

        private readonly ICaseDbForManage CaseDb;
        public CaseController(ICaseDbForManage db) {
            this.CaseDb = db;
        }

        public IActionResult Item(string id) {
            var user = CaseDb.Get(id);
            return View(user);
        }

        public IActionResult Index(
            CaseStatus status = CaseStatus.All,
            string userId = null,
            string articleId = null,
            SortPattern pattern = SortPattern.Newest,
            string query = null,
            int page = 1
        ) {
            var users = CaseDb.Index(status, userId, articleId, query, pattern, page, page_size);
            ViewBag.Query = query;
            ViewBag.StatusSel = status.ToSelectListItems();
            ViewBag.UserId = userId;
            ViewBag.ArticleId = articleId;
            ViewBag.PatternSel = pattern.ToSelectListItems();
            return View(users.ToList()); // PagedList don't support asp.net5 about Razor so far
        }

        private void BuildCreateView() {
            ViewBag.StatusSel = ArticleStatus.Unapproved.ToSelectListItems();
            ViewBag.TypeSel = ArticleType.Unknow.ToSelectListItems();
            ViewBag.VectorSel = ArticleVector.Text.ToSelectListItems();
        }

        public ActionResult Create() {
            BuildCreateView();
            return View(new Case());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Case model) {
            BuildCreateView();
            ModelState.Remove("CreatDate");
            if (!ModelState.IsValid) {
                ModelState.AddModelError("", "表单验证失败。");
                return View(model);
            }
            string failure;
            var user = CaseDb.Create(model, out failure);
            if (!string.IsNullOrEmpty(failure) || user == null) {
                ModelState.AddModelError("", failure ?? "新建失败");
                return View(model);
            }
            return RedirectToAction("Index");
        }

        private void BuildEditView(Case article) {
            ViewBag.StatusSel = ((CaseStatus)article.Status).ToSelectListItems();
        }

        public ActionResult Edit(string id) {
            var _case = CaseDb.Get(id);
            BuildEditView(_case);
            return View(_case);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Case model) {
            BuildEditView(model);
            ModelState.Remove("CreatDate");
            if (!ModelState.IsValid) {
                ModelState.AddModelError("", "表单验证失败。");
                return View(model);
            }
            string failure;
            var user = CaseDb.Update(model, out failure);
            if (!string.IsNullOrEmpty(failure) || user == null) {
                ModelState.AddModelError("", failure ?? "更新失败");
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id, string failure) {
            var user = CaseDb.Get(id);
            ViewBag.Failure = failure;
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id) {
            string failure;
            CaseDb.Delete(id, out failure);
            if (!string.IsNullOrEmpty(failure))
                return RedirectToAction("Delete", new { id = id, failure = failure });
            return RedirectToAction("Index");
        }
    }
}

Swallow.Manage/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Mvc;
using Swallow.Entity;
using Microsoft.AspNet.Authorization;
using MongoDB.Driver;
using MongoDB.Driver.Linq;
using Swallow.Core;

namespace Swallow.Manage.Controllers {
    [Authorize]
    public class UserController : Controller {
        private int page_size = 999;

        private readonly IUserDbForManage UserDb;
        public UserController(IUserDbForManage db) {
            this.UserDb = db;
        }

        public IActionResult Item(string id) {
            var user = UserDb.Get(id);
            return View(user);
        }

        public IActionResult Index(UserStatus status = UserStatus.All, string query = null, SortPattern pattern = SortPattern.Newest, int page = 1) {
            var users = UserDb.Index(status, query, pattern, page, page_size);
            ViewBag.StatusSel = status.ToSelectListItems();
            ViewBag.Query = query;
            return View(users.ToList()); // PagedList don't support asp.net5 about Razor so far
        }

        public ActionResult IndexLineOn() {
            return this.View();
        }

        public ActionResult Create() {
            return View(new User());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User model, string RolesParams) {
            ModelState.Remove("CreatDate");
            if (!ModelState.IsValid) {
                ModelState.AddModelError("", "表单验证失败。");
                return View(model);
            }

            string failure;
            var user = UserDb.Create(model, out failure);
            if (!string.IsNullOrEmpty(failure) || user == null) {
                ModelState.AddModelError("", failure ?? "新建失败");
                return View(model);
            }
            return RedirectToAction("Index");
        }

        private void BuildEditView(User user) {
            ViewBag.StatusSel = ((UserStatus)user.Status).ToSelectListItemsFilterNull();
        }

        public ActionResult Edit(string id) {
            var user = UserDb.Get(id);
            BuildEditView(user);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User model, string RolesParams) { // [Bind(Exclude = "Password,CreatDate")]
            ModelState.Remove("Password");
            ModelState.Remove("CreatDate"); // http://stackoverflow.com/a/25314838/346701
            if (!ModelState.IsValid) {
                ModelState.AddModelError("", "表单验证失败。");
                BuildEditView(model);
                return View(model);
            }

            string failure;
            var user = UserDb.Update(model, out failure);
            if (!string.IsNullOrEmpty(failure) || user == null) {
                ModelState.AddModelError("", failure ?? "更新失败");
                BuildEditView(model);
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id, string failure) {
            var user = UserDb.Get(id);
            ViewBag.Failure = failure;
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id) {
            string failure;
            UserDb.Delete(id, out failure);
            if (!string.IsNullOrEmpty(failure))
                return RedirectToAction("Delete", new { id = id, failure = failure});
            return RedirectToAction("Index");
        }
    }
}

Swallow.Manage/Views/User/Create.cshtml
@model Swallow.Entity.User
@{
    ViewBag.Title = "User - Create";
}

<div class="sub-navbar">
    <div style="margin-top:3px; float:right;">
        @using (Html.BeginForm("Index", "User", FormMethod.Get, new { @class = "form-inline" })) {
            <input type="text" class="input-m form-control" value="@ViewBag.Phone" name="Phone" placeholder="手机号/用户名/ID">
            <button type="submit" class="btn btn-primary">搜索</button>
        }
    </div>

    <ul class="nav sub-navbar-nav">
        <li class="">@Html.ActionLink("Index", "Index")</li>
        <li class="">@Html.ActionLink("在线用户", "IndexLineOn")</li>
        <li class="active">@Html.ActionLink("Create", "Create")</li>
    </ul>
</div>

<h2>User - Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Phone)
        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Phone)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password)
        @Html.TextBoxFor(m => m.Password, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Password)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Roles)
        @Html.TextArea("RolesParams", (string)ViewBag.RolesParams, new { @class = "form-control", rows = 3 })
        @Html.ValidationMessageFor(model => model.Roles)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Rank)
        @Html.TextBoxFor(model => model.Rank, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Rank)
    </div>
    <input type="submit" value="Submit" class="btn btn-default" />
}

<p class="mt10">
    @Html.ActionLink("Back to List", "Index")
</p>

@section Scripts {
    @Html.Partial("_ValidationScriptsPartial")
}

Swallow.Manage/Views/User/Delete.cshtml
@model Swallow.Entity.User

<h2>User - Delete</h2>

<p class="alert-danger">@ViewBag.Failure</p>

<h3>Are you sure you want to delete this?</h3>

@Html.DisplayForModel()

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" />
    </p>
    @Html.ActionLink("Back to List", "Index")
}

Swallow.Manage/Views/User/Edit.cshtml
@model Swallow.Entity.User
@{
    ViewBag.Title = "User - Edit";
}

<h2>User - Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Status)
        @Html.DropDownListFor(m => m.Status, (IEnumerable<SelectListItem>)ViewBag.StatusSel, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Phone)
        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Phone)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Rank)
        @Html.TextBoxFor(model => model.Rank, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Rank)
    </div>
    <input type="submit" value="Submit" class="btn btn-default" />
}

<p class="mt10">
    @Html.ActionLink("Back to List", "Index")
</p>

@section Scripts {
    @Html.Partial("_ValidationScriptsPartial")
}

Swallow.Manage/Views/User/Index.cshtml
@using Swallow.Entity
@model IEnumerable<User>

@{
    ViewBag.Title = "Users";
}

<div class="sub-navbar">
    <div style="margin-top:3px; float:right;">
        @using (Html.BeginForm("Index", "User", FormMethod.Get, new { @class = "form-inline" })) {
            <input type="text" class="form-control" value="@ViewBag.Query" name="query" placeholder="手机号/用户名">
            <button type="submit" class="btn btn-primary">搜索</button>
        }
    </div>

    <ul class="nav sub-navbar-nav">
        <li class="active">@Html.ActionLink("Index", "Index")</li>
        <li class="">@Html.ActionLink("在线用户", "IndexLineOn")</li>
        <li class="">@Html.ActionLink("Create", "Create")</li>
    </ul>
</div>

<table class="table">
    <tr>
        <th></th>
        <th>Name</th>
        <th>
            Status
            @Html.DropDownList("select_status", (IEnumerable<SelectListItem>)ViewBag.StatusSel, new { @class = "sel-query" })
        </th>
        <th>Role</th>
        <th>Rank</th>
        <th>CreateTime</th>
        <th>Cases</th>
        <th>Artilces</th>
        <th></th>
    </tr>
    @foreach (var item in Model) {
        <tr>
            <td>@item.Id - @item.Phone</td>
            <td>@item.Name</td>
            <td>@((UserStatus)item.Status)</td>
            <td>@((UserRole)item.Role)</td>
            <td>@item.Rank</td>
            <td>@item.CreateTime</td>
            <td>
                @Html.ActionLink(item.CaseCount.ToString(), "Index", "Case", new { userId = item.Id })
            </td>
            <td>
                @Html.ActionLink("articles", "Index", "Article", new { query = item.Id })
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

@section Scripts {
    <environment names="Development">
        <script src="~/js/index.js" asp-append-version="true"></script>
    </environment>
}

Swallow.Manage/Views/User/IndexLineOn.cshtml
@model dynamic

@{
    ViewBag.Title = "在线用户";
    //var users = (List<string>)Model;
}

<div class="sub-navbar">
    <div style="margin-top:3px; float:right;">
        @using (Html.BeginForm("Index", "User", FormMethod.Get, new { @class = "form-inline" })) {
            <input type="text" class="input-m form-control" value="@ViewBag.Phone" name="Phone" placeholder="手机号/用户名/ID">
            <button type="submit" class="btn btn-primary">搜索</button>
        }
    </div>

    <ul class="nav sub-navbar-nav">
        <li class="">@Html.ActionLink("Index", "Index")</li>
        <li class="active">@Html.ActionLink("在线用户", "IndexLineOn")</li>
        <li class="">@Html.ActionLink("Create", "Create")</li>
    </ul>
</div>

<h2>@ViewBag.Title</h2>
@*在线用户 @(users.Count) 个*@

Swallow.Manage/Views/User/Item.cshtml
@model Swallow.Entity.User

<h2>User - @Model.Name</h2>

@Html.DisplayForModel()

@Html.ActionLink("Back to List", "Index")